<?php

function parsley_js_tests_menu() {
  $items['testform'] = array(
    'title' => 'testform',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('parsley_js_test_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;

}

/**
 * Implements hook_parsley_js_forms
 */
function parsley_js_tests_parsley_js_forms() {
  return array(
    'parsley_js_test_form',
  );
}

function parsley_js_tests_form($form, &$form_state) {
  $form = array();

  $form['required'] = array(
    '#type' => 'textfield',
    '#title' => t('Test Required'),
    '#required' => TRUE,
  );

  $form['numeric'] = array(
    '#type' => 'textfield',
    '#title' => t('Test Numeric'),
    '#rules' => array(
      'numeric'
    ),
  );

  $form['length'] = array(
    '#type' => 'textfield',
    '#title' => t('Test Length'),
    '#rules' => array(
      'length[3, *]'
    ),
  );

  $form['range'] = array(
    '#type' => 'textfield',
    '#title' => t('Test Range'),
    '#rules' => array(
      'range[3, *]'
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Ok'
  );

  return $form;
}

